[formatting]
  align_comments        = true
  align_entries         = true
  allowed_blank_lines   = 2
  array_auto_collapse   = true
  array_auto_expand     = true
  array_trailing_comma  = true
  column_width          = 80
  compact_arrays        = true
  compact_entries       = false
  compact_inline_tables = false
  crlf                  = false
  indent_entries        = true
  indent_string         = "  "
  indent_tables         = true
  reorder_keys          = true
  trailing_newline      = true
