baseURL                       = "https://philong6297.github.io"
copyright                     = "test-cpr"
defaultContentLanguage        = "en"
enableEmoji                   = true
languageCode                  = "en"
paginate                      = 20
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle                 = "bw"
theme                         = "hugo-coder"
title                         = "LongLP"


[markup]
  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = true
    lineNumbersInTable = true
    noClasses          = true
    style              = 'onedark'
    tabWidth           = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe    = true
    xhtml     = true

[taxonomies]
  author   = "authors"
  category = "categories"
  series   = "series"
  tag      = "tags"

[caches]
  [caches.assets]
    maxAge = "10m"
  [caches.getcsv]
    maxAge = "10m"
  [caches.getjson]
    maxAge = "10m"
  [caches.getresource]
    maxAge = "10m"
  [caches.images]
    maxAge = "10m"
  [caches.modules]
    maxAge = "10m"

# Hugo Coders configuration
[params]
  author                = "Phi-Long Le"
  avatarURL             = "images/ava.png"
  colorScheme           = "auto"
  commit                = ""
  customCSS             = []
  customJS              = []
  customSCSS            = []
  dateFormat            = "January 2, 2006"
  description           = "Personal blog"
  enableTwemoji         = false
  favicon_16            = "images/favicon-16x16.png"
  favicon_32            = "images/favicon-32x32.png"
  hideColorSchemeToggle = false
  info                  = ["C++ Enthusiast"]
  katex                 = true
  keywords              = "blog,developer,personal"
  math                  = true
  maxSeeAlsoItems       = 10
  rtl                   = false
  since                 = "2021"
  touchIcon             = "images/apple-touch-icon.png"

  [[params.social]]
    icon   = "fa fa-2x fa-github"
    name   = "Github"
    url    = "https://github.com/philong6297"
    weight = 1
  [[params.social]]
    icon   = "fa fa-2x fa-linkedin"
    name   = "LinkedIn"
    url    = "https://www.linkedin.com/in/phi-long-le-91a06b223/"
    weight = 2

[menu]
  [[menu.main]]
    name   = "Blog"
    url    = "posts/"
    weight = 1
  [[menu.main]]
    name   = "About"
    url    = "about/"
    weight = 2
