# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
baseURL: "https://philong6297.github.io"
defaultContentLanguage: en
enableEmoji: true
languageCode: en
paginate: 20
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: bw
theme: hugo-coder
title: LongLP
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: onedark
    tabWidth: 2
  goldmark:
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
caches:
  assets:
    maxAge: 10m
  getcsv:
    maxAge: 10m
  getjson:
    maxAge: 10m
  getresource:
    maxAge: 10m
  images:
    maxAge: 10m
  modules:
    maxAge: 10m
params:
  author: Phi-Long Le
  avatarURL: images/ava.png
  colorScheme: auto
  commit: ""
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Personal blog
  enableTwemoji: false
  favicon_16: images/favicon-16x16.png
  favicon_32: images/favicon-32x32.png
  hideColorSchemeToggle: false
  info:
    - C++ Enthusiast
  katex: true
  keywords: blog,developer,personal
  math: true
  maxSeeAlsoItems: 10
  rtl: false
  since: 2021
  touchIcon: images/apple-touch-icon.png
  tocMinWordCount: 500
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/philong6297
      weight: 1
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/longlp/
      weight: 2
menu:
  main:
    - name: Blog
      url: posts/
      weight: 1
    - name: About
      url: about/
      weight: 2
