baseURL = "https://philong6297.github.io"
title = "LongLP"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
copyright = "test-cpr"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[caches]
  [caches.assets]
    maxAge = "10m"
  [caches.getcsv]
    maxAge = "10m"
  [caches.getjson]
    maxAge = "10m"
  [caches.getresource]
    maxAge = "10m"
  [caches.images]
    maxAge = "10m"
  [caches.modules]
    maxAge = "10m"

# Hugo Coders configuration
[params]
  author = "Phi-Long Le"
  info = ["C++ Enthusiast"]
  description = "Personal blog"
  keywords = "blog,developer,personal"
  avatarURL = "images/ava.png"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  dateFormat = "January 2, 2006"
  touchIcon = "images/apple-touch-icon.png"
  since = "2021"
  maxSeeAlsoItems = 10
  commit = ""
  rtl = false
  math = true
  katex = true
  colorScheme = "auto"
  hideColorSchemeToggle = false
  customCSS = []
  customSCSS = []
  customJS = []
  enableTwemoji = false

  [[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/philong6297"
  [[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/phi-long-le-91a06b223/"

[menu]
  [[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
  [[menu.main]]
    name = "About"
    weight = 2
    url = "about/"
