# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
baseURL: "https://philong6297.github.io"
defaultContentLanguage: en
enableEmoji: true
languageCode: en
paginate: 20
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: bw
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
theme: PaperMod
title: LongLP
copyright: Phi-Long Le

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: onedark
    tabWidth: 2
  goldmark:
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

caches:
  assets:
    maxAge: 10m
  getcsv:
    maxAge: 10m
  getjson:
    maxAge: 10m
  getresource:
    maxAge: 10m
  images:
    maxAge: 10m
  modules:
    maxAge: 10m

menu:
  main:
    - name: Archives
      url: archives
      weight: 5
    - name: Tags
      url: tags/
      weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Phi-Long Le
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: false # to disable highlight.js
    # disableFingerprinting: true
    favicon: images/favicon.ico
    favicon16x16: images/favicon-16x16.png
    favicon32x32: images/favicon-32x32.png
    apple_touch_icon: images/apple-touch-icon.png

  label:
    text: "LongLP"

  # home-info mode
  homeInfoParams:
    Title: Phi-Long Le
    Content: C++ Enthusiast

  socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/longlp/"
    - name: github
      url: "https://github.com/philong6297"
    - name: Rss
      url: "index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
